_format_version: "2.1"

services:
  - name: auth
    url: http://supabase-auth:9999
    routes:
      - name: auth-route
        paths:
          - /auth
        strip_path: false

  - name: rest
    url: http://supabase-rest:3000
    routes:
      - name: rest-route
        paths:
          - /rest
        strip_path: false

  - name: storage
    url: http://supabase-storage:5000
    routes:
      - name: storage-route
        paths:
          - /storage
        strip_path: false
